name: On-docker deploy Data Base

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker #Runner on-premise
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker compose deploy
        run: docker compose -f docker-compose.dev.yml up -d