name: On-Premise deploy Data Base

on:
  push:
    branches: [ "main", "test", "dev" ]

jobs:
  deploy:
    runs-on: kubernetes #Runner on-premise
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker compose deploy
        run: docker compose -f docker-compose.dev.yml up -d